import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import Layout from './Layout';
import { useAuth } from './AuthContext';
import { UserRole } from './types';
import { BookOpenIcon, CalendarIcon, BarChart2Icon, CheckCircleIcon } from './Icons';

const FeatureHighlight: React.FC<{ icon: React.ReactNode; title: string; description: string }> = ({ icon, title, description }) => (
    <div className="bg-[#0E1B17] p-4 rounded-xl ring-1 ring-white/10 flex items-start gap-4">
        <div className="bg-emerald-400/10 text-emerald-400 p-3 rounded-lg mt-1">{icon}</div>
        <div>
            <h3 className="font-semibold text-white">{title}</h3>
            <p className="text-sm text-gray-400">{description}</p>
        </div>
    </div>
);

const MentorOnboardingPage: React.FC = () => {
    const navigate = useNavigate();
    const location = useLocation();
    const { login } = useAuth();
    const { name, role, sport } = location.state || { role: UserRole.MENTOR, sport: 'Basketball' };

    const handleContinue = async () => {
        await login(role, sport);
    };

    return (
        <Layout title="Welcome" showBackButton={false}>
            <div className="flex flex-col h-full items-center justify-center text-center animate-fade-in">
                <div className="bg-emerald-500/10 p-4 rounded-full mb-6">
                    <div className="bg-emerald-500/20 p-3 rounded-full">
                        <CheckCircleIcon className="w-16 h-16 text-emerald-400" />
                    </div>
                </div>
                <h2 className="text-3xl font-bold">Application Submitted!</h2>
                <p className="text-gray-400 mt-2 mb-8 max-w-sm">
                    Thank you, {name || 'Coach'}. Your profile is under review. While you wait, here’s what you can do with your new coaching toolkit.
                </p>

                <div className="w-full space-y-4 text-left">
                    <FeatureHighlight 
                        icon={<BookOpenIcon />}
                        title="AI-Powered Drill Library"
                        description="Access and assign sport-specific drills generated by our AI coaching assistant."
                    />
                    <FeatureHighlight 
                        icon={<CalendarIcon />}
                        title="Session Management"
                        description="Easily schedule and manage one-on-one or group training sessions with your athletes."
                    />
                    <FeatureHighlight 
                        icon={<BarChart2Icon />}
                        title="Performance Tracking"
                        description="Monitor your athletes' progress with detailed analytics and AI-generated performance reports."
                    />
                </div>

                <div className="mt-8 w-full">
                    <button 
                        onClick={handleContinue}
                        className="w-full bg-emerald-500 text-white font-bold py-3 rounded-xl hover:bg-emerald-600 transition-colors"
                    >
                        Explore the Dashboard
                    </button>
                </div>
            </div>
        </Layout>
    );
};

export default MentorOnboardingPage;